export type IconName =
  | "Assembly"
  | "BrandCss3"
  | "BrandDocker"
  | "BrandGithub"
  | "BrandGoogle"
  | "BrandGraphql"
  | "BrandHtml5"
  | "BrandJavascript"
  | "BrandLinkedin"
  | "BrandPhp"
  | "BrandReact"
  | "BrandRedux"
  | "BrandRust"
  | "BrandSass"
  | "BrandSpeedtest"
  | "BrandTailwind"
  | "BrandTanstack"
  | "BrandTypescript"
  | "BrandVercel"
  | "BrandVisualStudio"
  | "BrandPowerShell"
  | "BrandVite"
  | "BrandVue"
  | "BrandXstate"
  | "ChartPie"
  | "CloudCog"
  | "Code"
  | "Components"
  | "Effect"
  | "FileTypeDoc"
  | "Palette"
  | "ServerCog"
  | "Sql"
  | "Stack"
  | "Svg"
  | "TestPipe"
  | "Webpack";

export type StackName =
  | "GitHub Actions"
  | "Knockout.js"
  | "Material UI"
  | "Next.js"
  | "Redux-saga"
  | "Shell Script"
  | "SQL Server"
  | "Tanstack DB"
  | "Tanstack Query"
  | "Tanstack Router"
  | "Tanstack Start"
  | "Visual Basic.NET"
  | "CSS"
  | "Docker"
  | "Effect"
  | "FlowType"
  | "GraphQL"
  | "HTML"
  | "JSDoc"
  | "JavaScript"
  | "Jest"
  | "Lit"
  | "Mocha"
  | "PHP"
  | "Preact"
  | "Puppeteer"
  | "React"
  | "Redux"
  | "Rust"
  | "SCSS"
  | "SQL"
  | "SVG"
  | "Tailwind"
  | "Tanstack"
  | "TypeScript"
  | "Vite"
  | "Vitest"
  | "Vue"
  | "XState"
  | "Webpack";
