export const ICON_GROUP_HOVER = {
  Assembly: "sm:group-hover:text-[#624FE8]",
  BrandCss3: "sm:group-hover:text-[#1572B6]",
  BrandGithub: "sm:group-hover:text-[#181717]",
  BrandGoogle: "sm:group-hover:text-[#4285F4]",
  BrandGraphql: "sm:group-hover:text-[#E10098]",
  BrandHtml5: "sm:group-hover:text-[#E34F26]",
  BrandJavascript: "sm:group-hover:text-[#F7DF1E]",
  BrandLinkedin: "sm:group-hover:text-[#0A66C2]",
  BrandPhp: "sm:group-hover:text-[#777BB4]",
  BrandReact: "sm:group-hover:text-[#61DAFB]",
  BrandRedux: "sm:group-hover:text-[#764ABC]",
  BrandRust: "sm:group-hover:text-[#E36F39]",
  BrandSass: "sm:group-hover:text-[#CC6699]",
  BrandSpeedtest: "sm:group-hover:text-[#5A52DE]",
  BrandTailwind: "sm:group-hover:text-[#06B6D4]",
  BrandTypescript: "sm:group-hover:text-[#3178C6]",
  BrandVercel: "sm:group-hover:text-[#000000]",
  BrandVite: "sm:group-hover:text-[#646CFF]",
  BrandVue: "sm:group-hover:text-[#4FC08D]",
  Components: "sm:group-hover:text-[#384EF6]",
  FileTypeDoc: "sm:group-hover:text-[#2F6DB5]",
  Sql: "sm:group-hover:text-[#F29111]",
  Svg: "sm:group-hover:text-[#FFB13B]",
  TestPipe: "sm:group-hover:text-[#83664B]",
};

export const ICON_COLORS = {
  Assembly: "text-[#624FE8]",
  BrandCss3: "text-[#1572B6]",
  BrandGithub: "text-[#181717]",
  BrandGoogle: "text-[#4285F4]",
  BrandGraphql: "text-[#E10098]",
  BrandHtml5: "text-[#E34F26]",
  BrandJavascript: "text-[#F7DF1E]",
  BrandLinkedin: "text-[#0A66C2]",
  BrandPhp: "text-[#777BB4]",
  BrandReact: "text-[#61DAFB]",
  BrandRedux: "text-[#764ABC]",
  BrandRust: "text-[#E36F39]",
  BrandSass: "text-[#CC6699]",
  BrandSpeedtest: "text-[#5A52DE]",
  BrandTailwind: "text-[#06B6D4]",
  BrandTanstack: "text-[#FF6154]",
  BrandTypescript: "text-[#3178C6]",
  BrandVercel: "text-[#000000]",
  BrandVisualStudio: "text-[#5C2D91]",
  BrandVite: "text-[#646CFF]",
  BrandVue: "text-[#4FC08D]",
  BrandXstate: "text-[#2C5282]",
  Components: "text-[#384EF6]",
  FileTypeDoc: "text-[#2F6DB5]",
  Sql: "text-[#F29111]",
  Stack: "text-[#68D391]",
  Svg: "text-[#FFB13B]",
  TestPipe: "text-[#83664B]",
};

export const LINK_CLASSES = {
  Assembly: "hover:decoration-[#624FE8]",
  BrandCss3: "hover:decoration-[#1572B6]",
  BrandGithub: "hover:decoration-[#181717]",
  BrandGoogle: "hover:decoration-[#4285F4]",
  BrandGraphql: "hover:decoration-[#E10098]",
  BrandHtml5: "hover:decoration-[#E34F26]",
  BrandJavascript: "hover:decoration-[#F7DF1E]",
  BrandLinkedin: "hover:decoration-[#0A66C2]",
  BrandPhp: "hover:decoration-[#777BB4]",
  BrandReact: "hover:decoration-[#61DAFB]",
  BrandRedux: "hover:decoration-[#764ABC]",
  BrandRust: "hover:decoration-[#E36F39]",
  BrandSass: "hover:decoration-[#CC6699]",
  BrandSpeedtest: "hover:decoration-[#5A52DE]",
  BrandTailwind: "hover:decoration-[#06B6D4]",
  BrandTypescript: "hover:decoration-[#3178C6]",
  BrandVercel: "hover:decoration-[#000000]",
  BrandVite: "hover:decoration-[#646CFF]",
  BrandVue: "hover:decoration-[#4FC08D]",
  Components: "hover:decoration-[#384EF6]",
  FileTypeDoc: "hover:decoration-[#2F6DB5]",
  Sql: "hover:decoration-[#F29111]",
  Svg: "hover:decoration-[#FFB13B]",
  TestPipe: "hover:decoration-[#83664B]",
};
